#!/bin/sh

if [ -n "$WAYLAND_DISPLAY" ] && [ -z "$DISABLE_WAYLAND" ]; then
  WAYLAND_OPTS="--enable-features=UseOzonePlatform --ozone-platform=wayland"
fi

$SNAP/opt/Mattermost/mattermost-desktop \
  --use-tray-icon --no-sandbox --disable-seccomp-filter-sandbox \
  "$WAYLAND_OPTS" \
    "$@"
